import Foundation

/// A legal document generated by DocumentEngine (versioned, not overwriting existing).
struct CaseDocument: Identifiable, Codable {
    let id: UUID
    let title: String
    let version: Int
    let content: String
    let createdAt: Date
}
