import SwiftUI

struct LegalDisclaimerView: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Legal Disclaimer")
                    .font(AppTypography.heading)
                    .foregroundColor(AppColors.textPrimary)

                Text("""
                Ask AI Lawyer is an informational and assistive tool only. It does not provide legal advice, does not create an attorney‑client relationship, and is not a substitute for a licensed attorney.

                Laws vary by jurisdiction and change over time. Any summaries, drafts, or suggestions generated by this app are for general reference only and may not apply to your situation. You should not rely on this app for legal decisions. Always consult a qualified attorney for advice specific to your case.

                Use of this app does not guarantee any outcome in any legal matter. The developers and operators of Ask AI Lawyer are not responsible for any actions you take or decisions you make based on content or outputs from this app.
                """)
                .font(AppTypography.body)
                .foregroundColor(AppColors.textPrimary)
                .fixedSize(horizontal: false, vertical: true)
            }
            .padding()
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .navigationTitle("Legal Disclaimer")
        .navigationBarTitleDisplayMode(.inline)
    }
}
